### ISSUE TITLE
Square Open Bracket instead I char In Logger

### ISSUE THREAD

**Issue by yusrenaltair** [antigloss/go#6]
I found the logs generated by this package are always preceded by the letter I. While at the end of the time marker there is a close bracket.
![image](https://user-images.githubusercontent.com/56446654/150625427-5578ddb9-9260-4ca8-bd58-a99fccbb0508.png)
So I'm looking at the code `logger.go` in function `genLogPrefix`
```go
func (l *Logger) genLogPrefix(buf *buffer, logLevel int32, skip int, t time.Time) {
	h, m, s := t.Clock()

	// time
	buf.tmp[0] = kLogLevelChar[logLevel]
	surplus := 0
	buf.WriteString("[") //I'm added this!
	if l.flag&ControlFlagLogDate != ControlFlagNone {
		year, mon, day := t.Date()
		buf.nDigits(4, 1, year, '0')
		buf.nDigits(2, 5, int(mon), '0')
		buf.nDigits(2, 7, day, '0')
		buf.tmp[9] = ' '
		surplus = 9
	}
//......
```
I added the code below on line 525
```go
buf.WriteString("[") //I'm added this!
```
And the result
![image](https://user-images.githubusercontent.com/56446654/150625604-0e1b6386-2fcd-4d8f-82a1-72b1ae125582.png)
is this the right way or ?
Thanks in advance 

Update : it turns out that char `I` is the abbreviation for Info, after re-reading the code and logs.

**Comment by antigloss** [comment]
I chose to ignore [ intentionally because it matters not with or without it. I is short for INFO. It could be T, I, W, E, or F based on the different log methods invoked.
